# Generated by Django 3.0.5 on 2020-04-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('scintific_rate', models.IntegerField()),
                ('contribution_rate', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('verification_status', models.CharField(max_length=50)),
                ('appropriate_grades_min', models.IntegerField(default=1, max_length=2)),
                ('appropriate_grades_max', models.IntegerField(default=12, max_length=2)),
                ('text', models.CharField(max_length=3000)),
                ('answer', models.CharField(max_length=3000)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('events', models.ManyToManyField(to='mhbank.Event')),
                ('question_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Themed_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=3000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Source'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='mhbank.Tag'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Event')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question')),
            ],
        ),
    ]
