# Generated by Django 3.0.5 on 2020-04-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='appropriate_grades_max',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='appropriate_grades_min',
            field=models.IntegerField(default=1),
        ),
    ]
