# Generated by Django 3.0.5 on 2020-04-22 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhbank', '0002_auto_20200422_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='scintific_rate',
            new_name='scientific_rate',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
