# Generated by Django 3.0.5 on 2020-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0003_auto_20200422_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
