# Generated by Django 3.0.5 on 2020-04-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0005_auto_20200423_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Source'),
        ),
    ]
