# Generated by Django 3.0.5 on 2020-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0006_auto_20200423_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='events',
            field=models.ManyToManyField(blank=True, to='mhbank.Event'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mhbank.Tag'),
        ),
    ]
