# Generated by Django 3.0.5 on 2020-04-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0007_auto_20200423_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Source'),
        ),
    ]
