# Generated by Django 3.0.5 on 2020-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0008_auto_20200423_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themed_q',
            old_name='name',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='question',
            name='sub_tags',
            field=models.ManyToManyField(blank=True, to='mhbank.Sub_tag'),
        ),
    ]
