# Generated by Django 3.0.5 on 2020-04-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0010_auto_20200423_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='last_change_date',
            new_name='published_date',
        ),
    ]
