# Generated by Django 3.0.5 on 2020-04-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0012_auto_20200423_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_added_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question'),
        ),
    ]
