# Generated by Django 3.0.5 on 2020-05-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0013_account_last_added_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_added_question',
        ),
    ]
