# Generated by Django 3.0.5 on 2020-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0014_remove_account_last_added_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contribution_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='scientific_rate',
            field=models.IntegerField(default=0),
        ),
    ]
