# Generated by Django 3.0.5 on 2020-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0016_auto_20200504_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
