# Generated by Django 3.0.5 on 2020-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0018_auto_20200505_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='verification_status',
            field=models.CharField(max_length=50),
        ),
    ]
