# Generated by Django 3.0.5 on 2020-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0019_auto_20200505_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
