# Generated by Django 3.0.5 on 2020-05-20 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0020_auto_20200520_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='appropriate_grades_min',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
