# Generated by Django 3.0.5 on 2020-05-20 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0021_auto_20200520_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('appropriate_grades_min', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('appropriate_grades_max', models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='appropriate_grades_max',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='hardness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Hardness'),
        ),
    ]
