# Generated by Django 3.0.5 on 2020-05-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0022_auto_20200520_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hardness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardness', to='mhbank.Hardness'),
        ),
    ]
