# Generated by Django 3.0.5 on 2020-05-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0024_auto_20200520_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hardness',
        ),
        migrations.AddField(
            model_name='hardness',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardness', to='mhbank.Question'),
        ),
    ]
