# Generated by Django 3.0.5 on 2020-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0025_auto_20200520_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
