# Generated by Django 3.0.5 on 2020-05-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0026_auto_20200520_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='last_change_date',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='appropriate_grades_max',
        ),
        migrations.RemoveField(
            model_name='question',
            name='appropriate_grades_min',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
    ]
