# Generated by Django 3.0.7 on 2020-07-21 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0027_auto_20200520_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('change_date', models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 55, 48, 912011, tzinfo=utc))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 55, 48, 908310, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='verification_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='themed_q',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Teach_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=1000, null=True)),
                ('expectations', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.TimeField(null=True)),
                ('generalـprocess', models.CharField(max_length=3000)),
                ('change_date', models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 55, 48, 912879, tzinfo=utc))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('change_date', models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 55, 48, 912445, tzinfo=utc))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mhbank.Question'),
        ),
    ]
