# Generated by Django 3.0.5 on 2020-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0028_question_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(verbose_name='date changed'),
        ),
    ]
