# Generated by Django 3.0.7 on 2020-07-21 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0028_auto_20200721_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 55, 1, 534443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 55, 1, 534870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 55, 1, 530764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teach_box',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 55, 1, 535304, tzinfo=utc)),
        ),
    ]
