# Generated by Django 3.0.6 on 2020-05-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0029_question_verification_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.CreateModel(
            name='Teach_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=1000, null=True)),
                ('expectations', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.TimeField(null=True)),
                ('generalـprocess', models.CharField(max_length=3000)),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question'),
        ),
    ]
