# Generated by Django 3.0.5 on 2020-05-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0029_question_verification_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.CreateModel(
            name='Teach_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=1000)),
                ('expectations', models.CharField(max_length=1000)),
                ('time', models.TimeField(null=True)),
                ('generalـprocess', models.CharField(max_length=3000)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question')),
                ('teach_box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Teach_box')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question'),
        ),
    ]
