# Generated by Django 3.0.5 on 2020-05-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0029_auto_20200520_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='change_date',
        ),
    ]
