# Generated by Django 3.0.7 on 2020-07-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0030_auto_20200721_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='teach_box',
            name='change_date',
        ),
    ]
