# Generated by Django 3.0.4 on 2020-07-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0030_auto_20200526_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mhbank.Question'),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hardness',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardnes', to='mhbank.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teach_box',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
