# Generated by Django 3.0.7 on 2020-07-21 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0030_auto_20200526_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 46, 48, 100074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mhbank.Question'),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 46, 48, 100513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 46, 48, 96405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teach_box',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 46, 48, 100944, tzinfo=utc)),
        ),
    ]
