# Generated by Django 3.0.7 on 2020-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0030_auto_20200721_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
