# Generated by Django 3.0.5 on 2020-05-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0031_question_change_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='change_date',
        ),
    ]
