# Generated by Django 3.0.7 on 2020-07-21 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0031_auto_20200721_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 29, 24, 632953, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='guidance',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 29, 24, 633378, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 29, 24, 629202, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='teach_box',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 29, 24, 633811, tzinfo=utc)),
        ),
    ]
