# Generated by Django 3.0.7 on 2020-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0031_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
