# Generated by Django 3.0.7 on 2020-07-21 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0031_auto_20200721_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 52, 8, 236123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 52, 8, 236580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 52, 8, 231746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teach_box',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 52, 8, 237034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='themed_q',
            name='text',
            field=models.TextField(),
        ),
    ]
