# Generated by Django 3.0.4 on 2020-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0032_auto_20200612_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='guidance',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='teach_box',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
