# Generated by Django 3.0.5 on 2020-05-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0032_remove_question_change_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publish_date',
            new_name='last_change_date',
        ),
    ]
