# Generated by Django 3.0.7 on 2020-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0032_question_change_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
