# Generated by Django 3.0.7 on 2020-07-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0033_remove_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidance',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teach_box',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
