# Generated by Django 3.0.4 on 2020-08-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0035_auto_20200730_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='publish_date',
        ),
    ]
