# Generated by Django 3.0.4 on 2020-08-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0036_remove_answer_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
