# Generated by Django 3.0.4 on 2020-12-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0038_auto_20201013_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mhbank.Source'),
        ),
    ]
