# Generated by Django 3.0.4 on 2020-12-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0039_auto_20201224_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Question')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.Account')),
            ],
        ),
    ]
