# Generated by Django 3.2.3 on 2021-05-25 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0041_auto_20201227_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccountScoreQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhbank.account')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mhbank.question')),
            ],
        ),
    ]
