# Generated by Django 3.2.3 on 2021-05-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhbank', '0043_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sub_tags',
            field=models.ManyToManyField(blank=True, to='mhbank.Sub_tag'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mhbank.Tag'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhbank.account'),
        ),
    ]
